const storeProducts = {
    clothes: {
        children: {
            main: [

                {
                    id: 1,
                    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d424dabd-ca03-4c22-8b8f-038627000ed6/sportswear-little-kids-tracksuit-rNpcd6.png",
                    productName: "Nike Sportswear Kid's Woven",
                    gender: "children",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "nike",
                    size: 6.5,
                    color: "red",
                },
                {
                    id: 2,
                    img: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/2df89846-5360-4b89-a061-4bce0618a785/sportswear-big-kids-tracksuit-extended-size-G9cqCl.png",
                    productName: "Nike Sportswear Big Kid's Tracksuit",
                    gender: "children",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "nike",
                    size: 7.0,
                    color: "black",
                },
                {
                    id: 3,
                    img: "https://jcpenney.scene7.com/is/image/JCPenney/DP0817202307192093M?hei=350&wid=350&op_usm=.4%2C.8%2C0%2C0&resmode=sharp2&op_sharpen=1",
                    productName: "Adidas Little boys",
                    gender: "children",
                    price: 89,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 6.5,
                    color: "black",
                },
                {
                    id: 4,
                    img: "https://i8.amplience.net/t/jpl/jd_product_list?plu=jd_593214_plc&qlt=85&exclusive=0&qlt=92&wid=320&hei=408&v=1&fmt=auto",
                    productName: "adidas Originals adicolor Tracksuit",
                    gender: "children",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7.0,
                    color: "pink",
                },
                {
                    id: 5,
                    img: "https://cdn-e.webinterpret.com/wi-ebay-pictures/EBAY/34/03/83/383043616942_images.linnlive.com_b94fb775765eeb48af2dac8978535bda_6e290828-ffa1-407a-ad1f-2e48cc249ff5.jpeg",
                    productName: "Kid's Boys T-Shirt Shorts 100% Cotton",
                    gender: "children",
                    price: 245.5,
                    priceCategory: "$120-$500",
                    brand: "Champion",
                    size: 6.5,
                    color: "grey",
                },
                {
                    id: 6,
                    img: "https://slimages.macysassets.com/is/image/MCY/products/4/optimized/24022504_fpx.tif?$filterlrg$&wid=327",
                    productName: "Little Girl's Classic Tee and Practice Shorts",
                    gender: "children",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "Champion",
                    size: 6.5,
                    color: "pink",
                },
                {
                    id: 7,
                    img: "https://slimages.macysassets.com/is/image/MCY/products/5/optimized/24020815_fpx.tif?$filterlrg$&wid=327",
                    productName: "Champion Kids White Dandelion ",
                    gender: "children",
                    price: 245.75,
                    priceCategory: "$120-$500",
                    brand: "Champion",
                    size: 7.0,
                    color: "white",
                },
                {
                    id: 8,
                    img: "https://www.cosmossport.cy/2348344-product_medium/champion-crewneck-t-shirt.jpg",
                    productName: "Champion Little Girl's Tee and Practice Shorts",
                    gender: "children",
                    price: 205.5,
                    priceCategory: "$120-$500",
                    brand: "champion",
                    size: 6.5,
                    color: "violet",
                },
                {
                    id: 9,
                    img: "https://popees.com/pub/media/catalog/product/cache/af5dcf3eb6b1e232451daa6282834a44/p/r/product-size_shirt.jpg",
                    productName: "Printed Half Sleeve Shirt",
                    gender: "children",
                    price: 115.34,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7.0,
                    color: "white",
                },
                {
                    id: 10,
                    img: "https://target.scene7.com/is/image/Target/GUEST_ba79ffa2-6093-4215-b13b-86a7930507b8?wid=488&hei=488&fmt=pjpeg",
                    productName: "Tolder Boy's Long Sleeve Shirt and Pants",
                    gender: "children",
                    price: 105.05,
                    priceCategory: "$0-$120",
                    brand: "fty",
                    size: 6.5,
                    color: "other",
                },
                {
                    id: 11,
                    img: "https://i.ebayimg.com/images/g/EKsAAOSw7-VjpJT4/s-l1200.webp",
                    productName: "Boy's Button Down Red Long Sleeve",
                    gender: "children",
                    price: 185,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "red",
                },
                {
                    id: 12,
                    img: "https://rukminim2.flixcart.com/image/850/1000/kmxsakw0/shirt/p/p/h/2-3-years-fksh5464-fm-kids-original-imagfqbkdmpmqng4.jpeg?q=90",
                    productName: "FM KIDS Boys Checkered Casual",
                    gender: "children",
                    price: 95,
                    priceCategory: "$0-$120",
                    brand: "LV",
                    size: 7,
                    color: "other",
                },
            ],
            dress:[
                {
                    id: 61,
                    img: "https://www.thehanfus.com/cdn/shop/products/WeddingDressBirthdayDressPageantDressesLaceEmbroideryDressPrincessChineseStyleDressTrystHanfus_2.png?v=1619574395",
                    productName: "Flower Girl Wedding Dress ",
                    gender: "children",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Forever21",
                    size: 6.5,
                    color: "white",
                  },
                  {
                    id: 62,
                    img: "https://ae01.alicdn.com/kf/Sb898c366c9654aa78c0602ee610fa197T/Girls-Wedding-Dress-For-Flower-Children-s-Summer-Design-Birthday-Party-Dresses-For-Girls-4-to.jpg",
                    productName: "Butterfly Chrome Style Dress",
                    gender: "children",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "Forever21",
                    size: 7.0,
                    color: "white",
                  },
                  {
                    id: 63,
                    img: "https://ae01.alicdn.com/kf/HTB1i0tKXMDD8KJjy0Fdq6AjvXXa1.jpg_640x640Q90.jpg_.webp",
                    productName: "Butterfly Chrome Style Dress",
                    gender: "children",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "white",
                  },
                  {
                    id: 64,
                    img: "https://ae01.alicdn.com/kf/S20d423875ba740a3ab26d2007c776c9bn.jpg_640x640Q90.jpg_.webp",
                    productName: "Elegance in Bloom Dress",
                    gender: "children",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "H&M",
                    size: 7.0,
                    color: "pink",
                  },
                  {
                    id: 65,
                    img: "https://estylecdn.com/manufcols/ashleylauren/current/zoomalt/8120_bi_front.jpg",
                    productName: "Children's Bloom Gown",
                    gender: "children",
                    price: 345.5,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "white",
                  },
                  {
                    id: 66,
                    img: "https://www.loveshackfancy.com/cdn/shop/files/MAZINADRESS-BERRYMOMENT-GD097-1744_003.jpg?v=1698942792&width=757",
                    productName: "Boxy Vicose Tunic Forever 21",
                    gender: "children",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "Forever21",
                    size: 6.5,
                    color: "pink",
                  },
                
            ],
            shirt:[
                {
                    id: 67,
                    img: "https://i5.walmartimages.com/seo/Boys-Light-Blue-Short-Sleeve-Polo-Shirt-Size-4-Case-of-36_f7907ba0-2f58-430e-9a2e-95e2ec8a04a6.a7a7ad1902715f118827df5e7f8d9fb8.jpeg",
                    productName: "Blue Duffy Boys Shirt",
                    gender: "children",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "blue",
                  },
                  {
                    id: 68,
                    img: "https://ae01.alicdn.com/kf/H2fb9cedf70e3417fba4cebbd147cc6473.jpg_640x640Q90.jpg_.webp",
                    productName: "Butterfly Chrome Style Shirt",
                    gender: "children",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "FTY",
                    size: 7.0,
                    color: "white",
                  },
                  {
                    id: 69,
                    img: "https://asset1.cxnmarksandspencer.com/is/image/mands/SD_04_T87_2448I_E0_X_EC_0?wid=1024&qlt=80",
                    productName: "Zara Polo Shirt Kids",
                    gender: "children",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "blue",
                  },
                  {
                    id: 70,
                    img: "https://cdn.mall.adeptmind.ai/https%3A%2F%2Flp2.hm.com%2Fhmgoepprod%3Fset%3Dquality%255B79%255D%252Csource%255B%252F1a%252F92%252F1a92b4ecd845410d389715282ab9217dddc9c411.jpg%255D%252Corigin%255Bdam%255D%252Ccategory%255B%255D%252Ctype%255BLOOKBOOK%255D%252Cres%255Bm%255D%252Chmver%255B1%255D%26call%3Durl%255Bfile%3A%2Fproduct%2Fmain%255D_640x.webp",
                    productName: "Elegance in Bloom Shirt",
                    gender: "children",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "H&M",
                    size: 7.0,
                    color: "white",
                  },
                  {
                    id: 71,
                    img: "https://target.scene7.com/is/image/Target/GUEST_47e07e21-f3b4-46bf-a7dd-16d657e05663?wid=488&hei=488&fmt=pjpeg",
                    productName: "Children's Bloom Shirt Boys",
                    gender: "children",
                    price: 345.5,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "blue",
                  },
                  {
                    id: 72,
                    img: "https://target.scene7.com/is/image/Target/GUEST_1c591735-9c9a-4ab5-a1c3-4daaa9491ac9?wid=488&hei=488&fmt=pjpeg",
                    productName: "Boxy Vicose Collared Shirt FTY 21",
                    gender: "children",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "FTY",
                    size: 6.5,
                    color: "white",
                  },                
            ]
        },
        men:{
            main:[
                {
                    id: 13,
                    img: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/b580200f-385a-4c9d-a6dd-a9c9d7f9c875/sportswear-hooded-woven-tracksuit-S0C9Ph.png",
                    productName: "Nike Sportswear Men's Hooded Woven",
                    gender: "men",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "nike",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 14,
                    img: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/a0593cb4-60c9-4036-8122-bf3d5a0107d2/club-poly-knit-tracksuit-ktgXg7.png",
                    productName: "Nike Club Men's Poly-Knit Tracksuit",
                    gender: "men",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "nike",
                    size: 7.0,
                    color: "other",
                  },
                  {
                    id: 15,
                    img: "https://i.ebayimg.com/images/g/IlcAAOSwcGtgOiIb/s-l1200.webp",
                    productName: "LG adidas OG Men's 50th Anniv",
                    gender: "men",
                    price: 89,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 16,
                    img: "https://images.asos-media.com/groups/adidas-originals-adicolor-tracksuit-in-green/18393-group-1",
                    productName: "adidas Originals adicolor Tracksuit",
                    gender: "men",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7.0,
                    color: "other",
                  },
                  {
                    id: 17,
                    img: "https://xsuit.com/cdn/shop/products/xsuit-4-0-dark-blue_1200x.jpg?v=1676295145",
                    productName: "Louis Vouitton Single-Breasted Wool",
                    gender: "men",
                    price: 445.5,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 18,
                    img: "https://i.pinimg.com/564x/43/73/46/43734605eab3c8f82980b4941fa0ec32.jpg",
                    productName: "Topman Suits Grey",
                    gender: "men",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "topMan",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 19,
                    img: "https://images.asos-media.com/products/topman-skinny-single-breasted-suit-jacket-in-grey/24114605-1-grey?$n_640w$&wid=513&fit=constrain",
                    productName: "Topman Skinny Single breasted Suit ",
                    gender: "men",
                    price: 345.75,
                    priceCategory: "$120-$500",
                    brand: "topMan",
                    size: 7.0,
                    color: "grey",
                  },
                  {
                    id: 20,
                    img: "https://i.pinimg.com/736x/4f/a1/06/4fa106de04ad4738240e3323297a8136.jpg",
                    productName: "Louis Vouitton Single-Breasted Midnight Green Suit",
                    gender: "men",
                    price: 305.5,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "green",
                  },
                  {
                    id: 21,
                    img: "https://media.boohooman.com/i/boohooman/bmm21671_black_xl?$product_image_category_page_very_small_mobile$",
                    productName: "adidas Oversized Snake Graphic T-Shirt",
                    gender: "men",
                    price: 115.34,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 22,
                    img: "https://cdna.lystit.com/520/650/n/photos/asos/32b36c50/pull-bear-Black-T-shirt-With-Death-Row-Records-Print.jpeg",
                    productName: "Nike Pull&Bear T-Shirt with DeathRow Records Print",
                    gender: "men",
                    price: 105.05,
                    priceCategory: "$0-$120",
                    brand: "nike",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 23,
                    img: "https://media.boohoo.com/i/boohoo/bmm32702_charcoal_xl/male-charcoal-plus-overdye-dove-graphic-t-shirt/?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit",
                    productName: "Plus Overdye Dove Graphic T-Shirt",
                    gender: "men",
                    price: 185,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 24,
                    img: "https://media.boohoo.com/i/boohoo/bmm50409_navy_xl?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit",
                    productName: "Aqua T Oxford Street Style",
                    gender: "men",
                    price: 95,
                    priceCategory: "$0-$120",
                    brand: "LV",
                    size: 7,
                    color: "other",
                  },                
            ],
            poloShirts:[
                {
                    id: 25,
                    img: "https://33000ft.com/cdn/shop/products/1_30845dc1-a210-4978-92d7-807c64824ecc.jpg?v=1673001510",
                    productName: "Men's UPF50+ Golf Polo Short Sleeve Collared",
                    gender: "men",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Polo",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 26,
                    img: "https://media.endclothing.com/media/catalog/product/_/4/_408321-X7331-9060_m1_1.jpg",
                    productName: "Gucci GRG Collar Polo",
                    gender: "men",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "Gucci",
                    size: 7.0,
                    color: "white",
                  },
                  {
                    id: 27,
                    img: "https://www.code-zero.com/uploads/media/68/59/6f/1634566427/polo-shirt-men-performance-front-washed-grey.jpg",
                    productName: "Polo Shirt Men Performance",
                    gender: "men",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Polo",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 28,
                    img: "https://bta.scene7.com/is/image/brownthomas/2000548003_01?$pdp_zoom$&$jpg$",
                    productName: "GUCCI Contrast Piquet Cotton Polo",
                    gender: "men",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "Gucci",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 29,
                    img: "https://i5.walmartimages.com/asr/feb5f348-ecba-447e-812a-7a4f6e01effc_1.469881b7ddd8ef62580c058aa72bbd24.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
                    productName: "Polo Authority Men's Tall Tech Pique",
                    gender: "men",
                    price: 345.5,
                    priceCategory: "$120-$500",
                    brand: "Polo",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 30,
                    img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1671476411/713997_XJETR_9088_001_100_0000_Light.jpg",
                    productName: "Gucci Cotton Jersey Polo",
                    gender: "men",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "Gucci",
                    size: 6.5,
                    color: "white",
                  },                
            ],
            tShirts:[
                {
                    id: 31,
                    img: "https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-stripe-accent-monogram-t-shirt-obsoletes-do-not-touch--FOTS37TR1613_PM2_Front%20view.jpg",
                    productName: "Strip Accent Monogram T-Shirt",
                    gender: "men",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 32,
                    img: "https://dopestreet.co/wp-content/uploads/2021/04/Off-White-Airport-Tape-Baggage-Black-Tee-Back-600x600.jpg",
                    productName: "Off-White Seeing Things",
                    gender: "men",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "Off White",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 33,
                    img: "https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-stripe-accent-monogram-t-shirt-obsoletes-do-not-touch--FOTS37TR1522_PM2_Front%20view.jpg",
                    productName: "Strip Accent Monogram T-Shirt",
                    gender: "men",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "red",
                  },
                  {
                    id: 34,
                    img: "https://www.mrporter.com/variants/images/1647597315003152/in/w2000_q60.jpg",
                    productName: "Logo-Print Cotton-Jersey T-Shirt",
                    gender: "men",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "Off White",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 35,
                    img: "https://www.kickscrew.com/cdn/shop/products/main-square_3f80b21b-e725-4003-ad54-ad944d629028_540x.jpg?v=1695378342",
                    productName: "OFF-WHITEXChampion MENS",
                    gender: "men",
                    price: 345.5,
                    priceCategory: "$120-$500",
                    brand: "Off White",
                    size: 6.5,
                    color: "red",
                  },
                  {
                    id: 36,
                    img: "https://images.stockx.com/images/OFF-WHITE-Mona-Lisa-Longsleeve-T-Shirt-Red.png?fit=fill&bg=FFFFFF&w=480&h=320&fm=jpg&auto=compress&dpr=2&trim=color&updated_at=1615596479&q=60",
                    productName: "OFF-WHITE MONA LISA Longsleeve  ",
                    gender: "men",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "topMan",
                    size: 6.5,
                    color: "grey",
                  },                
            ],
            
        },
        women:{
            main:[
                {
                    id: 43,
                    img: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/c72539aa-6a0f-4b2c-a1ef-9ea300066637/sportswear-nike-united-oversized-woven-tracksuit-jacket-Jdgq8K.png",
                    productName: "Nike United Woven's Oversized Women",
                    gender: "women",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "nike",
                    size: 6.5,
                    color: "green",
                  },
                  {
                    id: 44,
                    img: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/93b961d8-0f46-4ddc-836c-dbeab3bbda27/dri-fit-academy-tracksuit-QjPCzf.png",
                    productName: "Nike Dri-FIT Academy Women's Tracksuit",
                    gender: "women",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "nike",
                    size: 7.0,
                    color: "navyblue",
                  },
                  {
                    id: 45,
                    img: "https://cdna.lystit.com/400/500/tr/photos/zappos/5a34a791/adidas-originals-Black-Reflective-Tracksuit-Set.jpeg",
                    productName: "Adidas Originals Tracksuit",
                    gender: "women",
                    price: 109,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 46,
                    img: "https://i.pinimg.com/564x/14/af/bc/14afbcab52d50e2bc1e8108294a609e3.jpg",
                    productName: "adidas Originals adicolor Tracksuit",
                    gender: "women",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 47,
                    img: "https://i.etsystatic.com/36958048/r/il/d30290/4775444731/il_fullxfull.4775444731_2r98.jpg",
                    productName: "Louis Vouitton Single-Breasted Wool",
                    gender: "women",
                    price: 445.5,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 48,
                    img: "https://cdn.shopify.com/s/files/1/1025/3059/products/WOMENS_TEAL_EDITED_830x1230_crop_center.jpg?v=1658280930",
                    productName: "Topwoman Suits Navy-blue",
                    gender: "women",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "topMan",
                    size: 6.5,
                    color: "navyblue",
                  },
                  {
                    id: 49,
                    img: "https://www.bogliolimilano.com/dw/image/v2/AAGA_PRD/on/demandware.static/-/Sites-45/default/dw70e0f8f9/images/zoom/ZC0B95BGU07900276_0865_1.jpg?sw=1320&sh=1980&sm=fit",
                    productName: "Topman Skinny Single breasted Suit ",
                    gender: "women",
                    price: 345.75,
                    priceCategory: "$120-$500",
                    brand: "topMan",
                    size: 7.0,
                    color: "grey",
                  },
                  {
                    id: 50,
                    img: "https://italydirectclothing.com/cdn/shop/products/Bel-Lite-Grey_pic1-745x1113_1200x1200.jpg?v=1594395751",
                    productName: "Louis Vouitton Single-Breasted Midnight Grey Suit",
                    gender: "women",
                    price: 305.5,
                    priceCategory: "$120-$500",
                    brand: "LV",
                    size: 6.5,
                    color: "grey",
                  },
                  {
                    id: 51,
                    img: "https://media.boohoo.com/i/boohoo/azz37087_black_xl?w=537&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit",
                    productName: "Black Suit Spaghetti Strap Bodysuit",
                    gender: "women",
                    price: 115.34,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 52,
                    img: "https://n.nordstrommedia.com/id/sr3/7cf24fa7-b8b0-4488-9994-df4a97464e6a.jpeg?h=365&w=240&dpr=2",
                    productName: "Nike Pull&Bear Black Bodysuit",
                    gender: "men",
                    price: 105.05,
                    priceCategory: "$0-$120",
                    brand: "nike",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 53,
                    img: "https://media.boohoo.com/i/boohoo/dzz21574_black_xl/female-black-short-sleeve-bodysuit/?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit",
                    productName: "Adidas Black Overdye Bodysuit",
                    gender: "men",
                    price: 185,
                    priceCategory: "$120-$500",
                    brand: "adidas",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 54,
                    img: "https://n.nordstrommedia.com/id/sr3/03384fd3-9ccd-4ad8-b70a-fee494f8941d.jpeg?h=365&w=240&dpr=2",
                    productName: "Adidas Grey Bodysuits Oxford Street Style",
                    gender: "men",
                    price: 95,
                    priceCategory: "$0-$120",
                    brand: "adidas",
                    size: 7,
                    color: "grey",
                  },
                
            ],
            blouse:[
                {
                    id: 37,
                    img: "https://target.scene7.com/is/image/Target/GUEST_e93661d3-3c10-4ae0-926d-fc5e20ca556a?wid=488&hei=488&fmt=pjpeg",
                    productName: "Green Women's Satin Blouse",
                    gender: "women",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "green",
                  },
                  {
                    id: 38,
                    img: "https://cdn.mall.adeptmind.ai/https%3A%2F%2Flp2.hm.com%2Fhmgoepprod%3Fset%3Dquality%255B79%255D%252Csource%255B%252F0a%252F5c%252F0a5c03d6340c6ee8e56f01e4fe85f4522280a10c.jpg%255D%252Corigin%255Bdam%255D%252Ccategory%255B%255D%252Ctype%255BLOOKBOOK%255D%252Cres%255Bm%255D%252Chmver%255B1%255D%26call%3Durl%255Bfile%3A%2Fproduct%2Fmain%255D_large.webp",
                    productName: "H&M Boxy Vicose Blouse",
                    gender: "women",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "H&M",
                    size: 7.0,
                    color: "green",
                  },
                  {
                    id: 39,
                    img: "https://images.vestiairecollective.com/cdn-cgi/image/w=1246,q=70,f=auto,/produit/yellow-not-specified-zara-top-26942165-2_1.jpg",
                    productName: "Zara Blouse Yellow Size 6",
                    gender: "women",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "yellow",
                  },
                  {
                    id: 40,
                    img: "https://cdna.lystit.com/photos/hm/46e26bdd/hm-Black-Blouse.jpeg",
                    productName: "Elegance in Bloom Blouse",
                    gender: "women",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "H&M",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 41,
                    img: "https://target.scene7.com/is/image/Target/GUEST_6c7a86de-526c-426f-94a6-5f1270e032bc?wid=488&hei=488&fmt=pjpeg",
                    productName: "Women's Long Sleeve Loose Button-down Shirt",
                    gender: "women",
                    price: 345.5,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "yellow",
                  },
                  {
                    id: 42,
                    img: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F8c%2Ff6%2F8cf6d32420f81d791b98c74e0bcf4c2b2cef2af1.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
                    productName: "Boxy Vicose Blouse H&M",
                    gender: "women",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "H&M",
                    size: 6.5,
                    color: "green",
                  },                
            ],
            tunics:[
                {
                    id: 55,
                    img: "https://www.forever21.com/dw/image/v2/BFKH_PRD/on/demandware.static/-/Sites-f21-master-catalog/default/dw54ad60ea/1_front_750/00494939-01.jpg?sw=300&sh=450",
                    productName: "Black Women's Satin Tunic",
                    gender: "women",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Forever21",
                    size: 6.5,
                    color: "black",
                  },
                  {
                    id: 56,
                    img: "https://liveunlimitedlondon.com/cdn/shop/products/LU1243_H_e31e577a-2f6e-4b3d-8835-72bc4458bb61_800x.jpg?v=1579700240",
                    productName: "Jersey Satin Mix Tunic",
                    gender: "women",
                    price: 155.23,
                    priceCategory: "$120-$500",
                    brand: "Forever21",
                    size: 7.0,
                    color: "black",
                  },
                  {
                    id: 57,
                    img: "https://www.citychic.com.au/media/catalog/product/cache/1ef7fa863667a87bb19a34a82f4d98f0/210807NAVY-11.jpg",
                    productName: "Zara Tunic Navy Blue Size 6",
                    gender: "women",
                    price: 145.0,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "navyblue",
                  },
                  {
                    id: 58,
                    img: "https://di2ponv0v5otw.cloudfront.net/posts/2022/05/14/627f9310da10419adb456e81/m_627f9310da10419adb456e82.jpg",
                    productName: "Elegance in Bloom Blouse",
                    gender: "women",
                    price: 100,
                    priceCategory: "$0-$120",
                    brand: "H&M",
                    size: 7.0,
                    color: "other",
                  },
                  {
                    id: 59,
                    img: "https://static.zara.net/photos///2023/V/0/7/p/6795/101/250/2/w/824/6795101250_1_1_1.jpg?ts=1679048033138",
                    productName: "Women's Long Sleeve Loose Button-down Shirt",
                    gender: "women",
                    price: 345.5,
                    priceCategory: "$120-$500",
                    brand: "Zara",
                    size: 6.5,
                    color: "other",
                  },
                  {
                    id: 60,
                    img: "https://iconoflash.com/cdn/shop/products/TU012_NAV_1024x.jpg?v=1611164748",
                    productName: "Boxy Vicose Tunic Forever 21",
                    gender: "women",
                    price: 375,
                    priceCategory: "$120-$500",
                    brand: "Forever21",
                    size: 6.5,
                    color: "navyblue",
                  },                
            ]

        }

    }
}
module.exports = {storeProducts}